SPAM_KEYWORDS=[
    "win",
    "winner",
    "lottery",
    "claim",
    "reward",
    "free",
    "offer",
    "urgent",
    "click",
    "gift",
    "cash",
    "congratulation",
    "congratulations",
    "amazon",
    "flipkart",
    "meesho",
    "iphone",
    "bank",
    "verify",
    "otp",
    "password",
    "account",
    "limited",
    "discount",
    "bonus",
    "selected",
    "prize",
    "credit",
    "loan",
    "recharge",
    "call now",
    "act now",
    "buy now",
    "won",
    "click link",
    "link"
]